import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Dashboard from "@/components/Dashboard";
import Ket from "@/components/Ket";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={'${inter.className} bg-black'}>
          <div className="container-sidebar">
            <Sidebar />
          </div>
          <div className="container-dashboard">
            <Dashboard />
          </div>
          <div className="container-ket">
            <Ket />
          </div>
          {children}
        </body>
    </html>
  );
}
